# Generated by Django 3.1.5 on 2021-01-20 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_album_song'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['album_title']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['song_title']},
        ),
    ]
